name: Action Workflow

on:
  push:
  schedule:
    - cron: '0 */6 * * *'

env:
  TZ: Asia/Shanghai

jobs:
  run-fetch-arxiv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r ./requirements.txt
      
      - name: Build
        uses: actions/setup-node@master
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build
          
      - name: Run
        run: python3 "fetch_arxiv.py" "config_mac.json"
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./latest_papers
          github_token: ${{ secrets.DEPLOY_SECRET }}
          user_name: "yuuhe4fun"
          user_email: "hckrinston@hotmail.com"
          commit_message: "Github action update at `date '+%Y-%m-%d %H:%M:%S'`."
        
      - name: Commit
        # env:
        # GIT_NAME: "yuuhe4fun"
        # GIT_EMAIL: "hckrinston@hotmail.com"
        run: |
          git config --local user.name "yuuhe4fun"
          git config --local user.email "hckrinston@hotmail.com"
          git add .
          git commit -m "Github action update at `date '+%Y-%m-%d %H:%M:%S'`."
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MYGITHUB_TOKEN }}
          branch: master
